global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nifi'
    scheme: https
    metrics_path: /nifi-api/flow/metrics/prometheus
    static_configs:
      - targets: ['localhost:8443']
    tls_config:
      insecure_skip_verify: true
    authorization:
      type: Bearer
      credentials: "eyJraWQiOiI3M2RjMjMzNy01ZGRhLTRiNzgtYjJjOS03YTgzMTUzOWYwODAiLCJhbGciOiJFZERTQSJ9.eyJzdWIiOiJlMmE0OWM2Yy04YjM4LTQ4NmUtYjE1OC04NzJiMTFhNWVhOTQiLCJhdWQiOiJodHRwczovLzAuMC4wLjA6ODQ0MyIsIm5iZiI6MTc2MzY3Mzc3MSwiaXNzIjoiaHR0cHM6Ly8wLjAuMC4wOjg0NDMiLCJncm91cHMiOltdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJlMmE0OWM2Yy04YjM4LTQ4NmUtYjE1OC04NzJiMTFhNWVhOTQiLCJleHAiOjE3NjM3MDI1NzEsImlhdCI6MTc2MzY3Mzc3MSwianRpIjoiMWE1MmIzYTktOGY4My00NGE1LThlMGEtZWNlM2RkYTM4NmZmIn0.of-KrTmEH4sbK4I06c1QxxOdJrZF4PcTV9k7XxZIY9LU3O07Ii32pSwuNgL5pTqUnI-SuRKoNGpT8Ns_n59xCw"
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']